# file not downloaded in /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/slo-driven-deployment-governance.md
curl -o  /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/static/slo-driven-deployment-governance-601.png https://files.helpdocs.io/i5nl071jo5/articles/jws2znftay/1634844532487/clean-shot-2021-10-21-at-12-28-33.png
# file not downloaded in /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/slo-driven-deployment-governance.md
curl -o  /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/static/slo-driven-deployment-governance-602.png https://files.helpdocs.io/i5nl071jo5/articles/jws2znftay/1634856120356/clean-shot-2021-10-21-at-15-41-49-2-x.png
# file not downloaded in /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/slo-driven-deployment-governance.md
curl -o  /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/static/slo-driven-deployment-governance-603.png https://files.helpdocs.io/i5nl071jo5/articles/jws2znftay/1636584541766/clean-shot-2021-11-10-at-14-48-45-2-x.png
# file not downloaded in /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/slo-driven-deployment-governance.md
curl -o  /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/static/slo-driven-deployment-governance-604.png https://files.helpdocs.io/i5nl071jo5/articles/jws2znftay/1634859288101/clean-shot-2021-10-21-at-16-34-28-2-x.png
# file not downloaded in /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/slo-driven-deployment-governance.md
curl -o  /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/static/slo-driven-deployment-governance-605.png https://files.helpdocs.io/i5nl071jo5/articles/jws2znftay/1634859546331/clean-shot-2021-10-21-at-16-38-59-2-x.png
# file not downloaded in /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/slo-driven-deployment-governance.md
curl -o  /Users/douglasbothwell/Desktop/hd-docs-migrate/hd-convert/STAGE_docs/docs/service-reliability-management/service-reliability-management-onboard/static/slo-driven-deployment-governance-606.png https://files.helpdocs.io/i5nl071jo5/articles/jws2znftay/1634859678660/clean-shot-2021-10-21-at-16-40-28-2-x.png